spring:
  application:
    name: ai-worker

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_worker
    username: helpdesk
    password: helpdesk

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      enable-auto-commit: false
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      acks: all
      retries: 2147483647

      properties:
        enable.idempotence: true

    listener:
      ack-mode: manual

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: debug

ai:
  base-url: http://localhost:11434

knowledge-base:
  base-url: ${KNOWLEDGE_BASE_URL:http://localhost:8083}
  api-key: ${INTERNAL_API_KEY:dev-internal-key}

rag:
  confidence-threshold: 0.75
  default-top-k: 5

  model: qwen3:4b
  embedding-model: nomic-embed-text

  classification-temperature: 0.1
  answer-temperature: 0.4

  classification-top-p: 1.0
  answer-top-p: 0.9